language: cpp

dist: xenial

cache:
  - ccache
  - pip

before_install:
  - sudo apt-get install -y --no-install-recommends libprotobuf-dev protobuf-compiler libopencv-dev python3-pip python3-setuptools
  - sudo pip3 install gast numpy chainer onnx==1.3.0 onnx_chainer pytest

script:
  - bash ./scripts/run-travis-tests.sh

addons:
  apt:
    update: true

env:
  - CHAINER_BUILD_CHAINERX=1 CHAINERX_BUILD_CUDA=1
