language: cpp

dist: xenial

cache:
  - pip
  - ccache

before_install:
  - sudo apt-get install -y --no-install-recommends libprotobuf-dev protobuf-compiler libopencv-dev
  - pip install gast numpy chainer onnx==1.3.0 onnx_chainer

script:
  - bash ./scripts/run-travis-tests.sh

addons:
  apt:
    update: true
